// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Soporte API",
            "email": "soporte@sistal.com"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/empresas": {
            "get": {
                "description": "Obtiene lista de empresas (proveedores/clientes) con paginación",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Listar Empresas",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Número de página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Límite por página",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filtrar por tipo (1=Cliente, 2=Proveedor, 3=Ambos)",
                        "name": "id_tipo_empresa",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Buscar en nombre o RUT",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/prendas": {
            "get": {
                "description": "Obtiene lista paginada de prendas con filtros",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Prendas"
                ],
                "summary": "Listar Prendas",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Número de página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Límite por página",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filtrar por tipo de prenda",
                        "name": "id_tipo_prenda",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filtrar por género",
                        "name": "id_genero",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filtrar por temporada",
                        "name": "id_temporada",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Solo prendas maternales",
                        "name": "maternal",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Buscar en nombre o descripción",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\"nombre_prenda\"",
                        "description": "Campo para ordenar",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "\"asc\"",
                        "description": "Orden (asc|desc)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Crea una nueva prenda en el catálogo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Prendas"
                ],
                "summary": "Crear Prenda",
                "parameters": [
                    {
                        "description": "Datos de la prenda",
                        "name": "prenda",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreatePrendaDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/prendas/buscar": {
            "post": {
                "description": "Búsqueda avanzada con múltiples filtros",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Prendas"
                ],
                "summary": "Búsqueda Avanzada de Prendas",
                "parameters": [
                    {
                        "description": "Criterios de búsqueda",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SearchPrendasDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/prendas/{id_prenda}": {
            "get": {
                "description": "Obtiene información detallada de una prenda",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Prendas"
                ],
                "summary": "Obtener Prenda por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la prenda",
                        "name": "id_prenda",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Actualiza una prenda existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Prendas"
                ],
                "summary": "Actualizar Prenda",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la prenda",
                        "name": "id_prenda",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos a actualizar",
                        "name": "prenda",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdatePrendaDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina una prenda del catálogo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Prendas"
                ],
                "summary": "Eliminar Prenda",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la prenda",
                        "name": "id_prenda",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/prendas/{id_prenda}/proveedores": {
            "post": {
                "description": "Asocia un proveedor a una prenda",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Prendas"
                ],
                "summary": "Vincular Proveedor a Prenda",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la prenda",
                        "name": "id_prenda",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ID del proveedor",
                        "name": "proveedor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VincularProveedorDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/segmentos": {
            "get": {
                "description": "Obtiene lista de segmentos de negocio",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Listar Segmentos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/temporadas": {
            "get": {
                "description": "Obtiene lista de temporadas/campañas con paginación",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Temporadas"
                ],
                "summary": "Listar Temporadas",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Número de página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Límite por página",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filtrar por estado (40=Activa, 41=Inactiva, 42=Finalizada)",
                        "name": "id_estado_temporada",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Solo temporada activa",
                        "name": "activa_solo",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Crea una nueva temporada",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Temporadas"
                ],
                "summary": "Crear Temporada",
                "parameters": [
                    {
                        "description": "Datos de la temporada",
                        "name": "temporada",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateTemporadaDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/temporadas/activa": {
            "get": {
                "description": "Obtiene la temporada actualmente activa",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Temporadas"
                ],
                "summary": "Obtener Temporada Activa",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/temporadas/{id_temporada}/activar": {
            "patch": {
                "description": "Activa una temporada (desactiva automáticamente la temporada actual)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Temporadas"
                ],
                "summary": "Activar Temporada",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la temporada",
                        "name": "id_temporada",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tipos-prenda": {
            "get": {
                "description": "Obtiene lista de tipos de prenda disponibles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Listar Tipos de Prenda",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/uniformes": {
            "get": {
                "description": "Obtiene lista de uniformes con paginación y filtros",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Uniformes"
                ],
                "summary": "Listar Uniformes",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Número de página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Límite por página",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filtrar por segmento",
                        "name": "id_segmento",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Buscar en nombre o descripción",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Crea un nuevo conjunto de uniforme",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Uniformes"
                ],
                "summary": "Crear Uniforme",
                "parameters": [
                    {
                        "description": "Datos del uniforme",
                        "name": "uniforme",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateUniformeDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/uniformes/{id_uniforme}": {
            "get": {
                "description": "Obtiene información detallada de un uniforme con todas sus prendas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Uniformes"
                ],
                "summary": "Obtener Uniforme por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del uniforme",
                        "name": "id_uniforme",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Actualiza información básica del uniforme",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Uniformes"
                ],
                "summary": "Actualizar Uniforme",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del uniforme",
                        "name": "id_uniforme",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos a actualizar",
                        "name": "uniforme",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUniformeDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/uniformes/{id_uniforme}/prendas": {
            "post": {
                "description": "Agrega una prenda a un uniforme existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Uniformes"
                ],
                "summary": "Agregar Prenda a Uniforme",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del uniforme",
                        "name": "id_uniforme",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Prenda a agregar",
                        "name": "prenda",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AgregarPrendaUniformeDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/uniformes/{id_uniforme}/prendas/{id_prenda}": {
            "put": {
                "description": "Actualiza la cantidad de una prenda en el uniforme",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Uniformes"
                ],
                "summary": "Actualizar Cantidad de Prenda en Uniforme",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del uniforme",
                        "name": "id_uniforme",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID de la prenda",
                        "name": "id_prenda",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nueva cantidad",
                        "name": "cantidad",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ActualizarCantidadDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Elimina una prenda de un uniforme",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Uniformes"
                ],
                "summary": "Eliminar Prenda de Uniforme",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del uniforme",
                        "name": "id_uniforme",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID de la prenda",
                        "name": "id_prenda",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.StandardResponse"
                        }
                    }
                }
            }
        },
        "/garments/{id}": {
            "get": {
                "description": "Get garment details by ID (legacy endpoint)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Garments (Legacy)"
                ],
                "summary": "Get Garment (Legacy)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Garment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/master-data": {
            "get": {
                "description": "Get active campaign, garment types, sizes, and change reasons",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Master Data"
                ],
                "summary": "Get Master Data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.MasterDataResponse"
                        }
                    }
                }
            }
        },
        "/uniforms": {
            "get": {
                "description": "Get all uniforms with their garments (legacy endpoint)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Uniforms (Legacy)"
                ],
                "summary": "List Uniforms (Legacy)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.UniformeResponse"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.CampaignResponse": {
            "type": "object",
            "properties": {
                "activa": {
                    "type": "boolean"
                },
                "fechaFin": {
                    "type": "string"
                },
                "fechaInicio": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                }
            }
        },
        "controllers.IDLabelResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                }
            }
        },
        "controllers.MasterDataResponse": {
            "type": "object",
            "properties": {
                "campaign": {
                    "$ref": "#/definitions/controllers.CampaignResponse"
                },
                "changeReasons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.IDLabelResponse"
                    }
                },
                "garmentTypes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.IDLabelResponse"
                    }
                },
                "sizes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.IDLabelResponse"
                    }
                }
            }
        },
        "controllers.PrendaResponse": {
            "type": "object",
            "properties": {
                "fotoUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "tallas": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tipo": {
                    "type": "string"
                }
            }
        },
        "controllers.UniformeResponse": {
            "type": "object",
            "properties": {
                "descripcion": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nombre": {
                    "type": "string"
                },
                "prendas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.PrendaResponse"
                    }
                }
            }
        },
        "models.ActualizarCantidadDTO": {
            "type": "object",
            "required": [
                "cantidad"
            ],
            "properties": {
                "cantidad": {
                    "type": "integer",
                    "minimum": 1
                }
            }
        },
        "models.AgregarPrendaUniformeDTO": {
            "type": "object",
            "required": [
                "cantidad",
                "id_prenda"
            ],
            "properties": {
                "cantidad": {
                    "type": "integer",
                    "minimum": 1
                },
                "id_prenda": {
                    "type": "integer"
                }
            }
        },
        "models.CreatePrendaDTO": {
            "type": "object",
            "required": [
                "id_genero",
                "id_temporada",
                "id_tipo_prenda",
                "nombre_prenda",
                "tallas_disponibles"
            ],
            "properties": {
                "descripcion": {
                    "type": "string"
                },
                "id_genero": {
                    "type": "integer"
                },
                "id_temporada": {
                    "type": "integer"
                },
                "id_tipo_prenda": {
                    "type": "integer"
                },
                "maternal": {
                    "type": "boolean"
                },
                "nombre_prenda": {
                    "type": "string"
                },
                "tallas_disponibles": {
                    "type": "string"
                },
                "url_imagen": {
                    "type": "string"
                }
            }
        },
        "models.CreateTemporadaDTO": {
            "type": "object",
            "required": [
                "fecha_fin",
                "fecha_inicio",
                "nombre_temporada"
            ],
            "properties": {
                "fecha_fin": {
                    "type": "string"
                },
                "fecha_inicio": {
                    "type": "string"
                },
                "id_estado_temporada": {
                    "type": "integer"
                },
                "nombre_temporada": {
                    "type": "string"
                }
            }
        },
        "models.CreateUniformeDTO": {
            "type": "object",
            "required": [
                "id_segmento",
                "nombre_uniforme",
                "prendas"
            ],
            "properties": {
                "descripcion": {
                    "type": "string"
                },
                "id_segmento": {
                    "type": "integer"
                },
                "nombre_uniforme": {
                    "type": "string"
                },
                "prendas": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/models.PrendaUniformeCantidadDTO"
                    }
                }
            }
        },
        "models.ErrorInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {}
            }
        },
        "models.PrendaUniformeCantidadDTO": {
            "type": "object",
            "required": [
                "cantidad",
                "id_prenda"
            ],
            "properties": {
                "cantidad": {
                    "type": "integer",
                    "minimum": 1
                },
                "id_prenda": {
                    "type": "integer"
                }
            }
        },
        "models.SearchPrendasDTO": {
            "type": "object",
            "properties": {
                "generos": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "maternal": {
                    "type": "boolean"
                },
                "nombre": {
                    "type": "string"
                },
                "page": {
                    "type": "integer"
                },
                "proveedores": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "tallas": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "temporadas": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "tipos_prenda": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "models.StandardResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/models.ErrorInfo"
                },
                "errors": {},
                "message": {
                    "type": "string"
                },
                "meta": {},
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.UpdatePrendaDTO": {
            "type": "object",
            "properties": {
                "descripcion": {
                    "type": "string"
                },
                "id_genero": {
                    "type": "integer"
                },
                "id_temporada": {
                    "type": "integer"
                },
                "id_tipo_prenda": {
                    "type": "integer"
                },
                "maternal": {
                    "type": "boolean"
                },
                "nombre_prenda": {
                    "type": "string"
                },
                "tallas_disponibles": {
                    "type": "string"
                },
                "url_imagen": {
                    "type": "string"
                }
            }
        },
        "models.UpdateUniformeDTO": {
            "type": "object",
            "properties": {
                "descripcion": {
                    "type": "string"
                },
                "id_segmento": {
                    "type": "integer"
                },
                "nombre_uniforme": {
                    "type": "string"
                }
            }
        },
        "models.VincularProveedorDTO": {
            "type": "object",
            "required": [
                "id_empresa"
            ],
            "properties": {
                "id_empresa": {
                    "type": "integer"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Gestión de prendas del catálogo",
            "name": "Prendas"
        },
        {
            "description": "Gestión de uniformes y conjuntos de prendas",
            "name": "Uniformes"
        },
        {
            "description": "Gestión de temporadas/campañas",
            "name": "Temporadas"
        },
        {
            "description": "Datos maestros (tipos de prenda, segmentos, empresas)",
            "name": "Master Data"
        },
        {
            "description": "Endpoints legacy para compatibilidad",
            "name": "Uniforms (Legacy)"
        },
        {
            "description": "Endpoints legacy para compatibilidad",
            "name": "Garments (Legacy)"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8084",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "MS-Catalogo API",
	Description:      "API del Microservicio de Catálogo de Prendas y Uniformes\nGestiona el catálogo de prendas, uniformes, temporadas y datos maestros",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
